version: "3"

services:
  ftp:
    image: my-ftp:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21400:21100-21400
    environment:
      - PASV_ADDRESS=172.31.130.70
    volumes:
      - home_ftp:/var/ftp
      - log_ftp:/var/log/ftp

volumes:
  home_ftp:
  log_ftp:
