version: "3"

services:
  ftp:
    image: my-ftp:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - home_ftp:/var/ftp

volumes:
  home_ftp:
