version: "3"

services:
  ftp:
    # image: my-ftp:latest
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./conf:/etc/vsftpd
      - ./ftp:/var/ftp
      - ./logs:/var/log/vsftpd
