version: "3"

services:
  ftp:
    image: my-ftp:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    volumes:
      - ./vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - ./ftp:/var/ftp
