version: "3"

services:
  ftp:
    image: my-ftp:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    deploy:
      replicas: 1
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21500:21100-21500
    environment:
      - PASV_ADDRESS=172.31.130.70
    volumes:
      - /var/ftp:/var/ftp
      - /var/log/ftp:/var/log
