version: "3"

services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - "./ftp:/var/ftp"
    # - "./conf:/etc/vsftpd"
    # - "./logs:/var/log/vsftpd"
