version: "3"

services:
  ftp:
    image: my-ftp:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
    volumes:
      - home_ftp:/var/ftp

volumes:
  home_ftp:
